# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(662, 642)
        Dialog.setMaximumSize(QtCore.QSize(933, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMaximumSize(QtCore.QSize(111, 16))
        self.label.setObjectName("label")
        self.comboBox_selectProfile = QtWidgets.QComboBox(self.splitter)
        self.comboBox_selectProfile.setMaximumSize(QtCore.QSize(175, 23))
        self.comboBox_selectProfile.setObjectName("comboBox_selectProfile")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setMaximumSize(QtCore.QSize(91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_newProfileName = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_newProfileName.setObjectName("lineEdit_newProfileName")
        self.pushButton_save = QtWidgets.QPushButton(self.splitter)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.splitter)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.listWidget_irrelevant_gtex = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_irrelevant_gtex.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_irrelevant_gtex.setObjectName("listWidget_irrelevant_gtex")
        self.gridLayout.addWidget(self.listWidget_irrelevant_gtex, 1, 0, 1, 1)
        self.pushButton_makeIrrelevant_gtex = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_makeIrrelevant_gtex.setMaximumSize(QtCore.QSize(31, 51))
        self.pushButton_makeIrrelevant_gtex.setObjectName("pushButton_makeIrrelevant_gtex")
        self.gridLayout.addWidget(self.pushButton_makeIrrelevant_gtex, 1, 1, 1, 1)
        self.pushButton_makeRelevant_gtex = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_makeRelevant_gtex.setMaximumSize(QtCore.QSize(31, 51))
        self.pushButton_makeRelevant_gtex.setObjectName("pushButton_makeRelevant_gtex")
        self.gridLayout.addWidget(self.pushButton_makeRelevant_gtex, 1, 2, 1, 1)
        self.listWidget_relevant_gtex = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_relevant_gtex.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_relevant_gtex.setObjectName("listWidget_relevant_gtex")
        self.gridLayout.addWidget(self.listWidget_relevant_gtex, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.listWidget_irrelevant_cell_types = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_irrelevant_cell_types.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_irrelevant_cell_types.setObjectName("listWidget_irrelevant_cell_types")
        self.gridLayout_3.addWidget(self.listWidget_irrelevant_cell_types, 1, 0, 1, 1)
        self.pushButton_makeIrrelevant_cell_types = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_makeIrrelevant_cell_types.setMaximumSize(QtCore.QSize(31, 51))
        self.pushButton_makeIrrelevant_cell_types.setObjectName("pushButton_makeIrrelevant_cell_types")
        self.gridLayout_3.addWidget(self.pushButton_makeIrrelevant_cell_types, 1, 1, 1, 1)
        self.pushButton_makeRelevant_cell_types = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_makeRelevant_cell_types.setMaximumSize(QtCore.QSize(31, 51))
        self.pushButton_makeRelevant_cell_types.setObjectName("pushButton_makeRelevant_cell_types")
        self.gridLayout_3.addWidget(self.pushButton_makeRelevant_cell_types, 1, 2, 1, 1)
        self.listWidget_relevant_cell_types = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_relevant_cell_types.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_relevant_cell_types.setObjectName("listWidget_relevant_cell_types")
        self.gridLayout_3.addWidget(self.listWidget_relevant_cell_types, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Disease profile"))
        self.label.setText(_translate("Dialog", "Select disease profile"))
        self.label_2.setText(_translate("Dialog", "Save new profile"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Tissues"))
        self.label_3.setText(_translate("Dialog", "Not relevant"))
        self.label_4.setText(_translate("Dialog", "Relevant"))
        self.pushButton_makeIrrelevant_gtex.setText(_translate("Dialog", "<"))
        self.pushButton_makeRelevant_gtex.setText(_translate("Dialog", ">"))
        self.groupBox_3.setTitle(_translate("Dialog", "Cell types"))
        self.label_7.setText(_translate("Dialog", "Not relevant"))
        self.label_8.setText(_translate("Dialog", "Relevant"))
        self.pushButton_makeIrrelevant_cell_types.setText(_translate("Dialog", "<"))
        self.pushButton_makeRelevant_cell_types.setText(_translate("Dialog", ">"))

