# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(933, 692)
        Dialog.setMaximumSize(QtCore.QSize(933, 16777215))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMaximumSize(QtCore.QSize(111, 16))
        self.label.setObjectName("label")
        self.comboBox_selectProfile = QtWidgets.QComboBox(self.splitter)
        self.comboBox_selectProfile.setMaximumSize(QtCore.QSize(175, 23))
        self.comboBox_selectProfile.setObjectName("comboBox_selectProfile")
        self.pushButton_reset_default = QtWidgets.QPushButton(self.splitter)
        self.pushButton_reset_default.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton_reset_default.setMaximumSize(QtCore.QSize(101, 16777215))
        self.pushButton_reset_default.setObjectName("pushButton_reset_default")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setMaximumSize(QtCore.QSize(91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_newProfileName = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_newProfileName.setObjectName("lineEdit_newProfileName")
        self.pushButton_save = QtWidgets.QPushButton(self.splitter)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.listWidget_onTarget_hpa = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_onTarget_hpa.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_onTarget_hpa.setObjectName("listWidget_onTarget_hpa")
        self.gridLayout.addWidget(self.listWidget_onTarget_hpa, 1, 0, 1, 1)
        self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa.setObjectName("pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa")
        self.gridLayout.addWidget(self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa, 1, 4, 1, 1)
        self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa.setObjectName("pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa")
        self.gridLayout.addWidget(self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa, 1, 5, 1, 1)
        self.pushButton_onTarget_to_OffTarget_lowRisk_hpa = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_onTarget_to_OffTarget_lowRisk_hpa.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_onTarget_to_OffTarget_lowRisk_hpa.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_onTarget_to_OffTarget_lowRisk_hpa.setObjectName("pushButton_onTarget_to_OffTarget_lowRisk_hpa")
        self.gridLayout.addWidget(self.pushButton_onTarget_to_OffTarget_lowRisk_hpa, 1, 2, 1, 1)
        self.pushButton_offTarget_lowRisk_to_OnTarget_hpa = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_offTarget_lowRisk_to_OnTarget_hpa.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_offTarget_lowRisk_to_OnTarget_hpa.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_offTarget_lowRisk_to_OnTarget_hpa.setObjectName("pushButton_offTarget_lowRisk_to_OnTarget_hpa")
        self.gridLayout.addWidget(self.pushButton_offTarget_lowRisk_to_OnTarget_hpa, 1, 1, 1, 1)
        self.listWidget_offTarget_highRisk_hpa = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_offTarget_highRisk_hpa.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_offTarget_highRisk_hpa.setObjectName("listWidget_offTarget_highRisk_hpa")
        self.gridLayout.addWidget(self.listWidget_offTarget_highRisk_hpa, 1, 6, 1, 1)
        self.listWidget_offTarget_lowRisk_hpa = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_offTarget_lowRisk_hpa.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_offTarget_lowRisk_hpa.setObjectName("listWidget_offTarget_lowRisk_hpa")
        self.gridLayout.addWidget(self.listWidget_offTarget_lowRisk_hpa, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 3, 1, 1)
        self.pushButton_highRisk_to_lowRisk_hpo = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_highRisk_to_lowRisk_hpo.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_highRisk_to_lowRisk_hpo.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_highRisk_to_lowRisk_hpo.setObjectName("pushButton_highRisk_to_lowRisk_hpo")
        self.gridLayout_2.addWidget(self.pushButton_highRisk_to_lowRisk_hpo, 1, 1, 1, 1)
        self.pushButton_lowRisk_to_highRisk_hpo = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_lowRisk_to_highRisk_hpo.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButton_lowRisk_to_highRisk_hpo.setMaximumSize(QtCore.QSize(31, 90))
        self.pushButton_lowRisk_to_highRisk_hpo.setObjectName("pushButton_lowRisk_to_highRisk_hpo")
        self.gridLayout_2.addWidget(self.pushButton_lowRisk_to_highRisk_hpo, 1, 2, 1, 1)
        self.listWidget_highRisk_hpo = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_highRisk_hpo.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_highRisk_hpo.setObjectName("listWidget_highRisk_hpo")
        self.gridLayout_2.addWidget(self.listWidget_highRisk_hpo, 1, 3, 1, 1)
        self.listWidget_lowRisk_hpo = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_lowRisk_hpo.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_lowRisk_hpo.setObjectName("listWidget_lowRisk_hpo")
        self.gridLayout_2.addWidget(self.listWidget_lowRisk_hpo, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Disease profile"))
        self.label.setText(_translate("Dialog", "Select disease profile"))
        self.pushButton_reset_default.setText(_translate("Dialog", "Reset to default"))
        self.label_2.setText(_translate("Dialog", "Save new profile"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Human Protein Atlas - Tissue enrichment"))
        self.label_5.setText(_translate("Dialog", "Off-target tissues (high risk)"))
        self.label_4.setText(_translate("Dialog", "Off-target tissues (low risk)"))
        self.pushButton_offTarget_highRisk_to_offTarget_lowRisk_hpa.setText(_translate("Dialog", "<"))
        self.pushButton_offTarget_lowRisk_to_offTarget_highRisk_hpa.setText(_translate("Dialog", ">"))
        self.pushButton_onTarget_to_OffTarget_lowRisk_hpa.setText(_translate("Dialog", ">"))
        self.pushButton_offTarget_lowRisk_to_OnTarget_hpa.setText(_translate("Dialog", "<"))
        self.label_3.setText(_translate("Dialog", "On-target tissues"))
        self.groupBox_3.setTitle(_translate("Dialog", "Human Phenotype Ontology - Tissue-associated abnormalities"))
        self.label_7.setText(_translate("Dialog", "Tissues with low-risk abnormalities"))
        self.label_9.setText(_translate("Dialog", "Tissues with high-risk abnormalities"))
        self.pushButton_highRisk_to_lowRisk_hpo.setText(_translate("Dialog", "<"))
        self.pushButton_lowRisk_to_highRisk_hpo.setText(_translate("Dialog", ">"))

