# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 656)
        MainWindow.setMinimumSize(QtCore.QSize(653, 656))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setMinimumSize(QtCore.QSize(531, 491))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 11, 1)
        self.pushButton_insertFromText = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_insertFromText.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_insertFromText.setMaximumSize(QtCore.QSize(91, 16777215))
        self.pushButton_insertFromText.setObjectName("pushButton_insertFromText")
        self.gridLayout.addWidget(self.pushButton_insertFromText, 0, 1, 1, 1)
        self.pushButton_insertFromFile = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_insertFromFile.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_insertFromFile.setMaximumSize(QtCore.QSize(91, 40))
        self.pushButton_insertFromFile.setObjectName("pushButton_insertFromFile")
        self.gridLayout.addWidget(self.pushButton_insertFromFile, 1, 1, 1, 1)
        self.pushButton_clearList = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_clearList.setMaximumSize(QtCore.QSize(91, 23))
        self.pushButton_clearList.setObjectName("pushButton_clearList")
        self.gridLayout.addWidget(self.pushButton_clearList, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMaximumSize(QtCore.QSize(91, 16))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.lineEdit_disease_profile = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_disease_profile.setMaximumSize(QtCore.QSize(91, 16777215))
        self.lineEdit_disease_profile.setReadOnly(True)
        self.lineEdit_disease_profile.setObjectName("lineEdit_disease_profile")
        self.gridLayout.addWidget(self.lineEdit_disease_profile, 4, 1, 1, 1)
        self.pushButton_set_disease_profile = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_set_disease_profile.setMaximumSize(QtCore.QSize(91, 23))
        self.pushButton_set_disease_profile.setObjectName("pushButton_set_disease_profile")
        self.gridLayout.addWidget(self.pushButton_set_disease_profile, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMaximumSize(QtCore.QSize(91, 16777215))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 1, 1, 1)
        self.checkBox_ppi = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ppi.setObjectName("checkBox_ppi")
        self.gridLayout.addWidget(self.checkBox_ppi, 7, 1, 1, 1)
        self.checkBox_literature = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_literature.setObjectName("checkBox_literature")
        self.gridLayout.addWidget(self.checkBox_literature, 8, 1, 1, 1)
        self.pushButton_download = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_download.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_download.setMaximumSize(QtCore.QSize(91, 40))
        self.pushButton_download.setObjectName("pushButton_download")
        self.gridLayout.addWidget(self.pushButton_download, 9, 1, 1, 1)
        self.pushButton_openExistingData = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_openExistingData.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_openExistingData.setMaximumSize(QtCore.QSize(91, 40))
        self.pushButton_openExistingData.setObjectName("pushButton_openExistingData")
        self.gridLayout.addWidget(self.pushButton_openExistingData, 10, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(41, 16))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_status = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_status.setReadOnly(True)
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.gridLayout_2.addWidget(self.lineEdit_status, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 11, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 653, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionScoring_guide = QtWidgets.QAction(MainWindow)
        self.actionScoring_guide.setObjectName("actionScoring_guide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport_targets = QtWidgets.QAction(MainWindow)
        self.actionImport_targets.setObjectName("actionImport_targets")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOpen_existing_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_existing_file.setObjectName("actionOpen_existing_file")
        self.actionOpen_existing_output_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_existing_output_file.setObjectName("actionOpen_existing_output_file")
        self.menuFile.addAction(self.actionImport_targets)
        self.menuFile.addAction(self.actionOpen_existing_output_file)
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionScoring_guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TractaViewer"))
        self.pushButton_insertFromText.setText(_translate("MainWindow", "Get target list\n"
"from text"))
        self.pushButton_insertFromFile.setText(_translate("MainWindow", "Get target list\n"
"from file"))
        self.pushButton_clearList.setText(_translate("MainWindow", "Clear target list"))
        self.label_3.setText(_translate("MainWindow", "Disease profile:"))
        self.pushButton_set_disease_profile.setText(_translate("MainWindow", "Change"))
        self.label.setText(_translate("MainWindow", "Input a list of gene identifiers"))
        self.checkBox_ppi.setText(_translate("MainWindow", "Protein-protein\n"
"interactions"))
        self.checkBox_literature.setText(_translate("MainWindow", "Literature"))
        self.pushButton_download.setText(_translate("MainWindow", "Download\n"
"druggability data"))
        self.pushButton_openExistingData.setText(_translate("MainWindow", "Open existing\n"
"druggability data"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Download progress"))
        self.label_2.setText(_translate("MainWindow", "Status:"))
        self.lineEdit_status.setText(_translate("MainWindow", "Ready"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionScoring_guide.setText(_translate("MainWindow", "Scoring guide"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionImport_targets.setText(_translate("MainWindow", "Import targets"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionOpen_existing_file.setText(_translate("MainWindow", "Open existing file"))
        self.actionOpen_existing_output_file.setText(_translate("MainWindow", "Open existing output file"))

