# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewDataDialog(object):
    def setupUi(self, ViewDataDialog):
        ViewDataDialog.setObjectName("ViewDataDialog")
        ViewDataDialog.resize(1200, 800)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ViewDataDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(ViewDataDialog)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(ViewDataDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox_searchType = QtWidgets.QComboBox(ViewDataDialog)
        self.comboBox_searchType.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_searchType.setObjectName("comboBox_searchType")
        self.horizontalLayout.addWidget(self.comboBox_searchType)
        self.pushButton_search = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_search.setMaximumSize(QtCore.QSize(51, 16777215))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.pushButton_clear = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(41, 16777215))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout.addWidget(self.pushButton_clear)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(ViewDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_checkAll = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_checkAll.setMinimumSize(QtCore.QSize(61, 0))
        self.pushButton_checkAll.setMaximumSize(QtCore.QSize(61, 51))
        self.pushButton_checkAll.setObjectName("pushButton_checkAll")
        self.gridLayout.addWidget(self.pushButton_checkAll, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_checkSelected = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_checkSelected.setEnabled(False)
        self.pushButton_checkSelected.setMinimumSize(QtCore.QSize(91, 0))
        self.pushButton_checkSelected.setMaximumSize(QtCore.QSize(91, 16777215))
        self.pushButton_checkSelected.setObjectName("pushButton_checkSelected")
        self.verticalLayout.addWidget(self.pushButton_checkSelected)
        self.pushButton_clearSelection = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_clearSelection.setEnabled(False)
        self.pushButton_clearSelection.setMinimumSize(QtCore.QSize(91, 0))
        self.pushButton_clearSelection.setMaximumSize(QtCore.QSize(91, 16777215))
        self.pushButton_clearSelection.setObjectName("pushButton_clearSelection")
        self.verticalLayout.addWidget(self.pushButton_clearSelection)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_unCheckSelected = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_unCheckSelected.setEnabled(False)
        self.pushButton_unCheckSelected.setMinimumSize(QtCore.QSize(105, 0))
        self.pushButton_unCheckSelected.setMaximumSize(QtCore.QSize(105, 16777215))
        self.pushButton_unCheckSelected.setObjectName("pushButton_unCheckSelected")
        self.verticalLayout_2.addWidget(self.pushButton_unCheckSelected)
        self.pushButton_checkedOnly = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_checkedOnly.setEnabled(False)
        self.pushButton_checkedOnly.setMinimumSize(QtCore.QSize(105, 0))
        self.pushButton_checkedOnly.setMaximumSize(QtCore.QSize(105, 16777215))
        self.pushButton_checkedOnly.setObjectName("pushButton_checkedOnly")
        self.verticalLayout_2.addWidget(self.pushButton_checkedOnly)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.pushButton_createReports = QtWidgets.QPushButton(ViewDataDialog)
        self.pushButton_createReports.setEnabled(False)
        self.pushButton_createReports.setMinimumSize(QtCore.QSize(91, 51))
        self.pushButton_createReports.setMaximumSize(QtCore.QSize(91, 51))
        self.pushButton_createReports.setObjectName("pushButton_createReports")
        self.gridLayout.addWidget(self.pushButton_createReports, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)

        self.retranslateUi(ViewDataDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ViewDataDialog)

    def retranslateUi(self, ViewDataDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewDataDialog.setWindowTitle(_translate("ViewDataDialog", "Data viewer"))
        self.label.setText(_translate("ViewDataDialog", "Enter a list of genes to restrict data"))
        self.pushButton_search.setText(_translate("ViewDataDialog", "Search"))
        self.pushButton_clear.setText(_translate("ViewDataDialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ViewDataDialog", "Tab 1"))
        self.pushButton_checkAll.setText(_translate("ViewDataDialog", "Check\n"
"all"))
        self.pushButton_checkSelected.setText(_translate("ViewDataDialog", "Check selected"))
        self.pushButton_clearSelection.setText(_translate("ViewDataDialog", "Clear selection"))
        self.pushButton_unCheckSelected.setText(_translate("ViewDataDialog", "Uncheck selected"))
        self.pushButton_checkedOnly.setText(_translate("ViewDataDialog", "Show checked only"))
        self.pushButton_createReports.setText(_translate("ViewDataDialog", "Create reports"))

